### ISSUE TITLE
OperationMetadataBalanceUpdates vs. OperationBalanceUpdatesItem in @taquito 19

### ISSUE THREAD

**Issue by psmolinsky** [ecadlabs/taquito#2817]
**Description**
There are two different types `OperationMetadataBalanceUpdates` vs. `OperationBalanceUpdatesItem` in `@taquito/rpc`. They got quite inconsistent (have different fields) especially in v19 for *Oxford* protocol. Especially `bond_id` has conflicting type `string` vs. `BondId`. However, RPC schema has only single/same schema for balance updates.

**Comment by hui-an-yang** [comment]
hello @psmolinsky 

Thank you for reporting this. I have merged pr2816 to fix this. We decided to removed `OperationBalanceUpdatesItem` and use `OperationMetadataBalanceUpdates` for better maintenance. This will be included in the next release, in the mean time you can use preview build like this 
`npm i @taquito/taquito@19.0.2-0f6f366-- --registry https://npm.preview.tezostaquito.io/`

**Comment by psmolinsky** [comment]
Hello, I think you missed `delayed_operation_hash` which exists in RPC and it also existed on `OperationBalanceUpdatesItem`.

Sorry for very late remark, but [our development](https://dappetizer.dev/) is slowed down because of no funding.
